name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hacknarok2022
          heroku_email: "maciek2tr99@gmail.com"
          branch: "main"
          appdir: "backend"
